version: "3.9"

services:
  dwh_pipeline:
    build:
      context: .
      dockerfile: dockerfile.dwh
    ports:
      - "3000:3000"
    image: crhrbigdatadev.azurecr.io/hr-pipeline:latest

  dashboard:
    build:
      context: .
      dockerfile: dockerfile.dashboard
    ports:
      - "8501:8501"
    image: crhrbigdatadev.azurecr.io/hr-dashboard:latest