version: "3.9"

services:
  dwh_pipeline:
    build:
      context: .
      dockerfile: dockerfile.dwh
    ports:
      - "3000:3000"
    image: crhrbigdatadev.azurecr.io/hr-pipeline:latest

  dashboard:
    build:
      context: .
      dockerfile: dockerfile.dashboard
    volumes:
      #read-only bind mount
      - ./data_warehouse:/data_warehouse:ro
    ports:
      - "8501:8501"